# Generated by Django 5.0.2 on 2024-03-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='audiomodel',
            table='audio_specification_model',
        ),
        migrations.AlterModelTable(
            name='pcspecificationmodel',
            table='pc_specification',
        ),
        migrations.AlterModelTable(
            name='productdiscount',
            table='product_discount_model',
        ),
        migrations.AlterModelTable(
            name='productimagemodel',
            table='product_image_model',
        ),
        migrations.AlterModelTable(
            name='productmodel',
            table='product_model',
        ),
        migrations.AlterModelTable(
            name='sellerdatamodel',
            table='seller_data_model',
        ),
        migrations.AlterModelTable(
            name='smartphonemodel',
            table='smartphone_specification_model',
        ),
        migrations.AlterModelTable(
            name='televisionmodels',
            table='television_specification_model',
        ),
    ]
