# Generated by Django 5.0.2 on 2024-03-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_alter_audiomodel_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pcspecificationmodel',
            table='pc_specification_model',
        ),
    ]
