# Generated by Django 5.0.2 on 2024-03-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0003_alter_pcspecificationmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
