# Generated by Django 5.0.2 on 2024-03-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0004_alter_productmodel_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcspecificationmodel',
            name='spec_processor',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='smartphonemodel',
            name='spec_processor',
            field=models.CharField(max_length=25),
        ),
    ]
