# Generated by Django 5.0.2 on 2024-03-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0006_alter_smartphonemodel_spec_display_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphonemodel',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
