# Generated by Django 5.0.2 on 2024-03-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0007_alter_smartphonemodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagemodel',
            name='product_image',
            field=models.ImageField(upload_to='mob'),
        ),
    ]
