# Generated by Django 5.0.2 on 2024-03-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0008_alter_productimagemodel_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagemodel',
            name='product_image',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
