# Generated by Django 5.0.2 on 2024-03-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0010_alter_productimagemodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisionmodels',
            name='spec_resolution',
            field=models.CharField(max_length=30),
        ),
    ]
