# Generated by Django 5.0.2 on 2024-03-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0013_alter_pcspecificationmodel_spec_gpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcspecificationmodel',
            name='spec_os',
            field=models.CharField(max_length=20),
        ),
    ]
