# Generated by Django 5.0.2 on 2024-04-03 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0016_alter_productmodel_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='sellerapp.productmodel'),
        ),
        migrations.AlterField(
            model_name='pcspecificationmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='sellerapp.productmodel'),
        ),
        migrations.AlterField(
            model_name='smartphonemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='sellerapp.productmodel'),
        ),
        migrations.AlterField(
            model_name='televisionmodels',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv', to='sellerapp.productmodel'),
        ),
    ]
