# Generated by Django 5.0.2 on 2024-04-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0017_alter_audiomodel_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_description',
            field=models.TextField(max_length=400),
        ),
    ]
