# Generated by Django 5.0.2 on 2024-04-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0018_alter_productmodel_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_description',
            field=models.TextField(max_length=600),
        ),
    ]
