# Generated by Django 5.0.2 on 2024-04-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0019_alter_productmodel_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomodel',
            name='warranty',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pcspecificationmodel',
            name='warranty',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='smartphonemodel',
            name='warranty',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='televisionmodels',
            name='warranty',
            field=models.CharField(max_length=20),
        ),
    ]
