# Generated by Django 5.0.2 on 2024-05-13 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0020_alter_audiomodel_warranty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
