# Generated by Django 5.0.2 on 2024-06-01 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0021_productmodel_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdiscounts', to='sellerapp.productmodel'),
        ),
    ]
