# Generated by Django 5.0.2 on 2024-06-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0022_alter_productdiscount_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
