# Generated by Django 5.0.2 on 2024-03-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminregistrationmodel',
            table='admin_registration_model',
        ),
        migrations.AlterModelTable(
            name='eventmodel',
            table='event_model',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_category_model',
        ),
    ]
