# Generated by Django 5.0.2 on 2024-03-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_adminregistrationmodel_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
