# Generated by Django 5.0.2 on 2024-03-16 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_productcategory_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrandModel',
            fields=[
                ('brand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_img', models.ImageField(upload_to='brandimgs')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.productcategory')),
            ],
            options={
                'db_table': 'product_brand_model',
            },
        ),
    ]
