# Generated by Django 5.0.2 on 2024-03-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_productbrandmodel_brand_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_img',
            field=models.ImageField(null=True, upload_to='categories'),
        ),
    ]
