# Generated by Django 5.0.2 on 2024-03-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_productcategory_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.productcategory'),
        ),
    ]
