# Generated by Django 5.0.2 on 2024-03-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_eventmodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='category',
            new_name='event_category',
        ),
    ]
