# Generated by Django 5.0.2 on 2024-04-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_rename_category_eventmodel_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_img',
            field=models.ImageField(upload_to='adbanners'),
        ),
    ]
