# Generated by Django 5.0.2 on 2024-04-11 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0020_alter_audiomodel_warranty_and_more'),
        ('userapp', '0002_alter_cartdatamodel_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdatamodel',
            name='product_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.productimagemodel'),
        ),
    ]
