# Generated by Django 5.0.2 on 2024-04-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_cartdatamodel_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdatamodel',
            name='product_img',
        ),
    ]
