# Generated by Django 5.0.2 on 2024-05-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_reviewdatamodel_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatamodel',
            name='user_profile',
            field=models.ImageField(null=True, upload_to='Images'),
        ),
    ]
