# Generated by Django 5.0.2 on 2024-05-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_userdatamodel_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressdatamodel',
            name='phone_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
